version: '2'

services:
  db-svc:
    image: postgres:9.5
    container_name: db-svc
    networks:
      - dev
    ports:
      - 9999:5432
    environment:
      - POSTGRES_USER=goo
      - POSTGRES_PASSWORD=goo
      - POSTGRES_DB=goo

  usr-svc:
    build: .
    image: grpcproj
    networks:
      - dev
    ports:
      - 8080:8080
    depends_on:
      - db-svc
    restart: always

networks:
  dev:



